### PR TITLE
Refactored application

### PR DESCRIPTION
**Pull request by lfkeitel**
The changes shouldn't require any change to your Apache/Nginx configuration. I never had to change anything while I was making changes. The configuration will need to be changed to the new format however. If you have questions or want me to change something just let me know.

Both the enom and namecheap clients implement a common
interface for easier usage. Domains and DNSSEC records
are objects now which the clients return. The clients
DO NOT expose their underlying XML responses anymore.
We've gone up a level of abstraction. Instead they
return either a single literal value like the price
of a domain or an array or Domain or DNSSecKey objects.

All the class files have been moved to a separate folder
with an htaccess file to deny access from client browsers.
Clients should only access the files under the root. Really,
those need to be moved to a subfolder themselves for even
better containment, but we'll save that for later.

The configuration has been modified a bit as well. Each client
has a key in the config with their specific settings. The sample
config has been edited to show the new layout. This make it
so there doesn't need to be a separate server or username
variable for each client.

The stub API has been updated with Namecheap endpoints.

### CODE REVIEW

**Comment by nbebout** [comment]
Main page is mostly working, all my enom domains return "Locked" but the new version of index.php says No.

Also, manageDNSSEC is somehow running out of memory
[Sat Dec 09 18:23:25.055574 2017] [php7:notice] [pid 18177] [client 108.205.192.173:48339] PHP Notice:  Undefined index: submit in /var/www/html/dn/manageDNSSEC.php on line 9
[Sat Dec 09 18:23:25.657814 2017] [php7:error] [pid 18177] [client 108.205.192.173:48339] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/dn/classes/EnomClient.php on line 80

**Comment by lfkeitel** [comment]
Num 1 would be because i got the field Locked from enom when it should have been "lockstatus".
Num 2 is also because I didn't get the right field from the right object. I'll correct them and update the PR.

**Comment by lfkeitel** [comment]
Try it with the new commit.

**Comment by nbebout** [comment]
That solved those problems, but Namecheap's manageDNS is not working.  I added an echo and it looks like the URL that it calls has &Nameservers= and no list of nameservers afterwards

**Comment by lfkeitel** [comment]
It would help if I actually returned a value from array_map and array_filter. Try again and let me know the next bug you find.

**Comment by nbebout** [comment]
No more bugs found.  Merged.  I am filing another issue, but it's an issue that was around before you refactored the code.  If you have any ideas how to implement it, either send a PR or give me some ideas

**Pull request merged**
